#
# Copyright 2024 Clumio, a Commvault Company.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # Allow manual trigger for debugging the workflow.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: CI
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install
        run: make install-dev
      - name: lint
        run: make lint
      - name: mypy
        run: make mypy
      - name: Format check
        run: make format-check
      - name: Unit Tests
        run: make test
